GET http://localhost:3000/users



###
POST http://localhost:3000/users
Content-Type: application/json


{
    "id": "couple",
    "password": "123456"
}



###
POST http://localhost:3000/users/login
Content-Type: application/json


{
    "id": "couple",
    "password": "12dsdsa3456"
}